---
title: "BeatTB SES clean"
author: "Maryann Zhao"
date: "6/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(gridExtra)
library(pastecs)
library(qwraps2)
library(grid)
library(lattice)
library(ggplot2)
library(gt)
library(glue)
library(webshot)
library(GGally)
library(MASS)
library(ggpubr)
library(corrplot)
library(devtools)
library(ggbiplot)
library(RColorBrewer)
library(factoextra)
library(BBmisc)
library(e1071)
library(formattable)
library(qwraps2)
library(vcd)
library(tidyr)
library(knitr)
#library(kableExtra)
library(finalfit)
library(DescTools)
library(cowplot)
library(vegan)
library(gtsummary)
knitr::opts_knit$set(root.dir = "~/Dropbox (MIT)/Murray_Lab/BeatTB/Dec2021")
```

Import Data
```{r}
#read in beattb data
beattb <- read_csv("~/Dropbox (MIT)/Murray_Lab/BeatTB/Sept2021/beattb_demo_202108.csv")
beattb_out_full <- read_csv("~/Dropbox (MIT)/Murray_Lab/BeatTB/Dec2021/20211221_ladder_retestfull.csv")
```

### WAMI: Water and Sanitation 
```{r}
#Water and Sanitation - 4 is improved, 0 is unimproved
beattb <- beattb %>%
  mutate(h2o = if_else(drk_wt_src <=5, 4, 0)) %>% #improved water
  mutate(sanitation = if_else(toilet_type >= 5 & toilet_type <=10, 4, 0)) %>% #improved sanitation
  rowwise() %>%
  dplyr::mutate(h2o_sani = sum(c_across(h2o:sanitation))) #add water and sanitation together
```


### WAMI: Eduation
```{r}
#Convert birthdays to Date type
beattb$FechaNacimiento <- as.Date(beattb$FechaNacimiento, "%m/%d/%y")
beattb$FechaNacimiento <- ifelse(beattb$FechaNacimiento > Sys.Date(), format(beattb$FechaNacimiento, "19%y-%m-%d"), format(beattb$FechaNacimiento))

#Calculate education/maternal education score by dividing distribution into 9 categories
beattb <- beattb %>%
  rowwise() %>%
  mutate(age = trunc(as.numeric(difftime(as.Date("2021-06-07"), as.Date(FechaNacimiento), unit="weeks"))/52.25)) %>%
  mutate(edu_score = ifelse(age >=20, as.numeric(edu_yrs), as.numeric(gd_edu_yrs))) %>%
  mutate(edu_score_nml = cut(edu_score, breaks = seq(0, 20, 20/9), labels = c(0:8), include.lowest = TRUE, right = TRUE)) #edu_score_nml = 9 equal categories

#Find pts missing income or guardian education values
beattb_na <- beattb[is.na(beattb$income) | is.na(beattb$edu_score_nml),]
#Rmv pts w/o data (Total 608 -> 595)
beattb <- beattb[!is.na(beattb$income) & !is.na(beattb$edu_score_nml),]
```


### WAMI: Income
```{r}
#Recode remaining Income data to categorical 1-9 -> no 0 were reported
#1, <400 | 2, 400 to 600|3, 600 to 700|4, 700 to 800 | 5, 800 to 900 |6, 900 to 1000 | 7, 1000 to 1300 |8, 1300 to 1650 | 9,  > 1650 |0, doesn't know.
beattb$income[beattb$income < 400 & beattb$income > 9] <- 1
beattb$income[beattb$income >= 400 & beattb$income < 600] <- 2
beattb$income[beattb$income >= 600 & beattb$income < 700] <- 3
beattb$income[beattb$income >= 700 & beattb$income < 800] <- 4
beattb$income[beattb$income >= 800 & beattb$income < 900] <- 5
beattb$income[beattb$income >= 900 & beattb$income < 1000] <- 6
beattb$income[beattb$income >= 1000 & beattb$income < 1300] <- 7
beattb$income[beattb$income >= 1300 & beattb$income < 1650] <- 8
beattb$income[beattb$income >= 1650] <- 9

```

### WAMI: PCA Assets
```{r}
#beattb.pca - compute PCA based on 15 assets
#center shifts variables to be zero centered, scale indicates variables should have unit variance before analysis
beattb.pca <- prcomp(beattb[40:54], center = TRUE, scale.=TRUE)

#Select PC1 
beattb$pc1 <- beattb.pca$x[,1]

#create 9 quantiles for PCA and cut PCA scores into 9 categories
len <- (max(beattb.pca$x[,1])- min(beattb.pca$x[,1]))
brk <- seq(min(beattb.pca$x[,1]), max(beattb.pca$x[,1]), len/9)
brk[10] <- Inf
beattb <- beattb %>%
  mutate(pc1_nml = cut(pc1, breaks = brk, labels = c(0:8), include.lowest = TRUE, right = FALSE)) #pc1_nml - 9 equal categories
```

### WAMI: Calculate final score
```{r}
#WAMI categorized based on splitting 32 into even 10 categories
beattb$pc1_nml <- as.numeric(levels(beattb$pc1_nml))[beattb$pc1_nml]
beattb$edu_score_nml <-as.numeric(levels(beattb$edu_score_nml))[beattb$edu_score_nml]
beattb <- beattb %>%
  rowwise() %>%
  mutate(income_nml = income-1) %>%
  dplyr::mutate(WAMI = sum(h2o_sani, pc1_nml, edu_score_nml, income_nml)) %>% #calculate WAMI
  #mutate(WAMI_std = ntile(WAMI, 10)) %>% #std - 10 deciles
  mutate(WAMI_nml = cut(WAMI, breaks = seq(0, 32, 3.2), labels = c(1:10), include.lowest = TRUE, right = TRUE))  # nml - equally categories for 10 pts

##WAMI rescaled from 32-points to 10-points using rank correlation approach
#determine number of observations in each step of ladder
ladder_counts <- dplyr::count(beattb, SES_scale)

#order the WAMI scores using radix sort
beattb_order <- beattb[order(beattb$WAMI),]

#rescale WAMI to 10-points
beattb_order$WAMI_np <- NA
j <- 1
k <- 0
score <- 1
for (i in ladder_counts$n){
  #samples <- ladder_counts$n[i]
  #print(samples)
  print(j)
  print (k)
  print(i)
  print(score)
  k <- k + i
  beattb_order$WAMI_np[j:k] <- score
  score <- score + 1
  j <- j + i
}
```



### Table 4
```{r}
#Determine difference between WAMI and ladder scores
beattb_order <- beattb_order %>%
  mutate(delta = WAMI_np - SES_scale) %>% #delta = WAMI nonparametric - ladder
  mutate(same = ifelse(delta == 0, 1, 0)) %>%
  mutate(deltaone = ifelse(delta == 1 | delta ==-1, 1, 0)) %>%
  mutate(delta2 = ifelse(delta == 2 | delta ==-2, 1, 0)) %>%
  mutate(delta3 = ifelse(delta == 3 | delta ==-3, 1, 0)) %>%
  mutate(delta4 = ifelse(delta >= 4 | delta <= -4, 1, 0)) %>%
  mutate(delta_2SD = ifelse(delta > 4 | delta < -4, 1, 0)) 
  
fig5a_var <- beattb_order %>% dplyr::select(same, deltaone, delta2, delta3, delta4, delta_2SD)
fig5a <- tbl_summary(fig5a_var, 
                    label = list(
                      same ~ "Same group", 
                      deltaone ~ "Moved 1 group",
                      delta2 ~ "Moved 2 groups",
                      delta3 ~ "Moved 3 groups",
                      delta4 ~ "Moved 4 or more groups", 
                      delta_2SD ~ "Top 20 of moved 4 or more groups"),
                    statistic = list(all_categorical() ~ "{p}%"),
                    ) 
fig5a
```
### Identifying Outliers
```{r}
#standard deviation of difference between WAMI and ladder
out_sd <- sd(beattb_order$delta)

beattb_outliers_4 <- beattb_order[beattb_order$delta4 == 1, ]
beattb_outliers_ext <- beattb_order[beattb_order$delta_2SD == 1, ]

beattb_outliers_4_order <- beattb_outliers_4[order(beattb_outliers_4$delta),]

write.csv(beattb_outliers_4_order, "beattb_outliers_4_order_wrong.csv")
```

###--- Table 3 WAMI and Ladder Correlation Coefficients
```{r}
#spearman correlation
pear <- cor.test(beattb_order$SES_scale, beattb_order$WAMI_np, method = "spearman")
pear.ladder_income <- cor.test(beattb_order$SES_scale, beattb_order$income_nml, method = "spearman")
pear.ladder_ws<- cor.test(beattb_order$SES_scale, beattb_order$h2o_sani, method = "spearman")
pear.ladder_ass<- cor.test(beattb_order$SES_scale, beattb_order$pc1_nml, method = "spearman")
pear.ladder_edu<- cor.test(beattb_order$SES_scale, beattb_order$edu_score_nml, method = "spearman")
pear
pear.ladder_income
pear.ladder_ws
pear.ladder_ass
pear.ladder_edu
#piecewise correlation for 0-3, 4-7, 8-10
beattb_order_low <- beattb_order[beattb_order$SES_scale <= 3, ]
pear.ladder_low <- cor.test(beattb_order_low$SES_scale, beattb_order_low$WAMI_np, method = "spearman")
beattb_order_mid <- beattb_order[beattb_order$SES_scale >3 & beattb_order$SES_scale <8, ]
pear.ladder_mid <- cor.test(beattb_order_mid$SES_scale, beattb_order_mid$WAMI_np, method = "spearman")
beattb_order_high <- beattb_order[beattb_order$SES_scale >= 8, ]
pear.ladder_high <- cor.test(beattb_order_high$SES_scale, beattb_order_high$WAMI_np, method = "spearman")
pear.ladder_low
pear.ladder_mid
pear.ladder_high

 
#Dec 2021 retest
#replace outliers with retest ladder scores
 beattb_order <- beattb_order %>%
  mutate(SES_retest2 = SES_scale)
 
j = 1
for (i in match(beattb_out_full$PTID, beattb_order$PTID)){
  beattb_order$SES_retest2[i] <- beattb_out_full$ladder_retest[j]
  j <- j + 1
}
beattb_order$SES_retest2 <- as.numeric(beattb_order$SES_retest2)
#spearman correlation between ladder retest and WAMI
pear.retest2 <- cor.test(beattb_order$SES_retest2, beattb_order$WAMI_np, method = "pearson")
pear.retest2
```


### Table 4
```{r}
#contingency table of ladder vs updated WAMI
wami_tbl <- table(beattb_order$SES_scale, beattb_order$WAMI_np, dnn = c("SES Ladder", "WAMI"))
wami_tbl_prop <- prop.table(wami_tbl)

#Fleiss-Cohen gives greater importance to near disagreements
k.fc <- Kappa(wami_tbl, weights = "Fleiss-Cohen")
k.fc
```

### Figure 3 Frame of reference bias 
```{r}
#if WAMI was < 5, on average did ladder scores move up 
beattb_moveup <- beattb_order[beattb_order$WAMI_np < 5,]
beattb_movedown <- beattb_order[beattb_order$WAMI_np > 5,]
beattb_5 <- beattb_order[beattb_order$WAMI_np == 5,]
beattb_order <- beattb_order %>%
  mutate(level5 = ifelse(WAMI_np < 5, 1, ifelse(WAMI_np == 5, 2, 3)))
beattb_order$level5 <- as.factor(beattb_order$level5)

#violin plots comparing deltas
fig3b <- beattb_order %>%
    ggplot(aes(x = level5)) + 
    geom_violin(mapping = aes(y = delta), alpha = 0.5, trim = FALSE, fill = "#00AFBB")  +
    geom_boxplot(aes(y = delta), width = 0.1) + 
    theme_minimal() + 
    xlab ("Above or Below WAMI of 5") + 
    ylab ("WAMI - Ladder") +
    theme_pubr()

```


### Paper Figures and Tables
```{r}
#select variables for summary table 1
fig_beattb <- beattb %>% mutate(
  Female = ifelse(gender == 2, 1, 0), 
  
  EducationalLevel = dplyr::case_when(
                  edu_level == 1 | edu_level == 2 ~ "2) Primary School", 
                  edu_level == 3 | edu_level == 4 ~ "3) High school", 
                  edu_level == 5 | edu_level == 6 | edu_level == 7 | edu_level == 8 ~ "4) Technical studies or University", 
                  edu_level == 13 ~ "1) No school at all"), 
  subHS = ifelse(edu_level == 1 | edu_level == 2 | edu_level == 3 | edu_level == 4 | edu_level == 13, 1, 0), 
  
  Employed = ifelse(have_job == 1, 1, 0), 
  perBedroom = ifelse(hh_num/br_num >= 3, "1) greater than or equal to 3", "2) less than 3"),
  improvedH2O = ifelse(h2o == 4, 1, 0), 
  improvedSew = ifelse(sanitation == 4, 1, 0), 
  Income = dplyr::case_when(
                  income_nml == 0 | income_nml == 1 | income_nml == 2 | income_nml == 3 | income_nml == 4 ~ "1) < 400-900", 
                  income_nml == 5 | income_nml == 6 ~ "2) 900-1300", 
                  income_nml == 7 | income_nml == 8 ~ "3) > 1300"
  ), 
  Roof = dplyr::case_when(
                  roof == 1 ~ "Etemit", 
                  roof == 2 ~ "Straw", 
                  roof == 3 ~ "Metal", 
                  roof == 4 ~ "Wood", 
                  roof == 5 ~ "Brick",
                  roof == 6 ~ "Calamine",
                  roof == 7 ~ "Drywall"
  )
  # Diff5 = dplyr::case_when(
  #                 level5 == 1 ~ "WAMI < 5",
  #                 level5 == 2 ~ "WAMI = 5",
  #                 level5 == 3 ~ "WAMI > 5"
  # )
  ) 
#select fig 1 variables 
fig1_var <- fig_beattb %>% dplyr::select(Female, age, EducationalLevel, edu_yrs, Employed, SES_scale, improvedH2O, improvedSew, Income)

# summarize cohort characteristics
theme_gtsummary_compact()
theme_gtsummary_journal("jama")
tbl1 <- tbl_summary(fig1_var, 
                    statistic =  list(
                      #all_continuous() ~ "{median} ({IQR})"),
                      all_categorical() ~ "{n} ({p}%)"), 
                    label = list(
                      edu_yrs ~ "Educational Years", 
                      age ~ "Age",
                      EducationalLevel ~ "Educational Level", 
                      SES_scale ~ "Self-reported SES Ladder", 
                      improvedH2O ~ "Improved Drinking Water", 
                      improvedSew ~ "Improved Sanitation")
                    )
tbl1
tbl1 %>%
  as_gt() %>%
  gt::gtsave("fig1_summary.html")
# summary WAMI 
fig1b_var <- fig_beattb %>% dplyr::select(iron_board, bed, chair, sofa, cupboard, table, electric_fan, radio, computer, TV, mobile_phone, fridge, watch, bike, bank)
fig1b <- tbl_summary(fig1b_var, 
                    statistic =  list(
                      all_categorical() ~ "{p}%"), 
                    label = list(
                      iron_board = "Iron (either charcoal or electric)", 
                      bed = "Bed", 
                      chair = "Chair or Bench", 
                      sofa = "Sofa", 
                      cupboard = "Cupboard", 
                      table = "Table", 
                      electric_fan = "Electric Fan", 
                      radio = "Radio or Transistor", 
                      computer = "Computer", 
                      TV = "Television", 
                      mobile_phone = "Mobile Phone", 
                      fridge = "Refrigerator", 
                      watch = "Watch or Clock", 
                      bike = "Bike", 
                      bank = "Bank Account")
                    )
fig1b
fig1b %>%
  as_gt() %>%
  gt::gtsave("fig1b_assets.png")
#figure 2 WAMI raw 
fig2a <- beattb_order %>% ggplot(aes(x = WAMI)) +
        geom_bar(fill = "#00AFBB", color = "#00AFBB", alpha = 0.2) +
        xlab("WAMI") + 
        geom_vline(aes(xintercept = median(as.numeric(WAMI))),col='red',size=0.5, linetype= "longdash") +
        theme_pubr()

fig2a
ggsave(filename = "fig2_WAMI_raw.png", plot = fig2)

#Figure 3a: ladder raw and rescaled WAMI
fig2b <- beattb_order %>% ggplot(aes(x = WAMI_np)) +
        geom_bar(fill = "#00AFBB", color = "#00AFBB", alpha = 0.2) +
        theme_pubr() +
        xlab("WAMI/Self-reported Ladder") + 
        geom_vline(aes(xintercept = median(WAMI_np)),col='red',size=0.5, linetype= "longdash") +
        scale_x_continuous(labels = label_number(accuracy = 1))
fig2b

#Figure 3b: comparing WAMI and ladder using violin plots
fig3a <- beattb_order %>%
  ggplot(aes(x = SES_scale, y = WAMI_np)) +
  geom_violin(aes(group = cut_width(SES_scale, 1)), color = "#00AFBB", fill = "#00AFBB", alpha = 0.2) +
  scale_x_discrete(limits = 0:11) +
  geom_boxplot(aes(group = cut_width(SES_scale, 1)), width=0.1) + 
  theme_pubr() +
  scale_y_continuous(labels = label_number(accuracy = 1)) +
  xlab("Self-reported Ladder SES") + 
  ylab("WAMI") +
  geom_abline(intercept = 2*out_sd, slope = 1, col = 'red', lty=2, lwd=0.5, alpha = 0.5) +
  geom_abline(intercept = -2*out_sd, slope = 1, col = 'red', lty=2, lwd=0.5, alpha = 0.5)  
fig3a

fig2 <- plot_grid(fig2a, fig2b, nrows=2, labels = LETTERS[1:2])
fig2
ggsave(filename = "fig2_wami_ladder.png", plot = fig2)

fig3 <- plot_grid(fig3a, fig3b, nrows=1, labels = LETTERS[1:2])
fig3
ggsave(filename = "fig3_wami_ladder.png", plot = fig3)

#Figure 4: initial ladder vs diffference between ladder scores
#compare outliers retest scores to non-outliers retest
outlier <- beattb_out_full[beattb_out_full$outlier == 1,]
nonoutlier <- beattb_out_full[beattb_out_full$outlier == 0,]
beattb_out_full <- beattb_out_full[,1:6]

#collect all characteristics of retested participants
retest2 <- beattb_order[beattb_order$PTID %in% beattb_out_full$PTID, ]
beattb_retest2 <- merge(x = retest2, y = beattb_out_full, by = "PTID", all.x = TRUE)
colnames(beattb_retest2)[89] <- "delta_retest"


#Figure 4: Comparing ladder retest scores to initial
fig4a <- beattb_retest2 %>% ggplot(aes(x = SES_scale, y = delta_retest)) +
  geom_jitter(aes(color = as.factor(outlier)), shape=16, position=position_jitter(0.2), show.legend = FALSE) +
  geom_abline(intercept = 0, slope = 0, lty = 3, color = "grey")+
  scale_color_manual(values = c("#00AFBB", "#F4A582")) +
  scale_x_discrete(limits = 1:10) +
  theme_pubr() +
  coord_fixed(ratio = 1) +
  xlab("Initial Ladder Score") + 
  ylab("Initial - Retest (Ladder Score)")
fig4a

fig4b <- beattb_retest2 %>% ggplot(aes(x = SES_scale, y = WAMI_np)) +
  geom_jitter(aes(color = as.factor(outlier)), shape=16, position=position_jitter(0.2), show.legend = FALSE) +
  geom_abline(intercept = 0, slope = 1, lty = 3, color = "grey") +
  theme_pubr() +
  scale_x_discrete(limits = 1:10) +
  scale_y_discrete(limits = 1:10) +
  expand_limits (x = c(0, 10), y = c(0, 10)) +
  scale_color_manual(values = c("#00AFBB", "#F4A582"))+
  coord_fixed(ratio = 1) +
  xlab("Ladder Initial") +
  ylab("WAMI")

fig4b

fig4c <- beattb_retest2 %>% ggplot(aes(x = ladder_retest, y = WAMI_np)) +
  geom_jitter(aes(color = as.factor(outlier)), shape=16, position=position_jitter(0.2), show.legend = FALSE) +
  geom_abline(intercept = 0, slope = 1, lty = 3, color = "grey") +
  theme_pubr() +
  scale_x_discrete(limits = 1:10) +
  scale_y_discrete(limits = 1:10) +
  expand_limits (x = c(0, 10), y = c(0, 10)) +
  scale_color_manual(values = c("#00AFBB", "#F4A582"))+
  coord_fixed(ratio =1) +
  xlab("Ladder Retest") +
  ylab("WAMI")

fig4 <- plot_grid(fig4a, fig4b, fig4c, nrows=1, labels = LETTERS[1:3])
ggsave(filename = "fig4_retest.png", plot = fig4)

```


